### ISSUE TITLE
Small improving

### ISSUE THREAD

**Issue by JuanVqz** [abodmicheal/React-projects#1]
- [x] Abodbnb  project doesn't have `.gitignore`

```bash
cp Netflix\ UI\ Web\ App/.gitignore Abodbnb/
```

- [x]  Single-ChannelMessanger, I think the new messages should be at the top like so

the main change is replace "asc" to "desc" in src/Msg.js file
```sh
db.collection('msg').orderBy("timestamp", "desc").onSnapshot(snapshot => {
```

![Screen Shot 2021-03-13 at 21 51 17](https://user-images.githubusercontent.com/7331511/111056765-52b3ed80-8447-11eb-8930-a01bdc750299.png)

**Comment by abodmicheal** [comment]
I'll work on it, Thank you
